---
title: "FIESTA - Spatial Tools"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{FIESTA - Spatial Tools}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---


## FIESTA Overview
The R package, FIESTA (Forest Inventory ESTimation and Analysis) is a research estimation tool for analysts that work with sample-based inventory data from the U.S. Department of Agriculture, Forest Service, Forest Inventory and Analysis (FIA) Program to accommodate: unique population boundaries, different evaluation time periods, customized stratification schemes, non-standard variance equations, integration of multi-scale remotely-sensed data and other ancillary information, and interaction with other modeling and estimation tools from CRAN R's library of packages. FIESTA contains a collection of functions that can access FIA databases, summarize and compile plot and spatial data, and generate estimates with associated sampling errors. 


Functions are organized by type or objective and are named with a corresponding prefix: 

**Core Functions**

* Database tools (DB) - functions for querying and extracting data from FIA's national database.
* Data tools (dat) - functions for summarizing and exploring FIA data.
* Spatial tools (sp) - functions for manipulating and summarizing spatial data.

**Estimation Modules**

* Green-Book (GB) - functions for FIA’s standard ‘Green-Book’ estimators.
* Photo-Based (PB) - functions for supplementary photo-based estimators.
* Small Area (SA) - functions for integration with available small area estimators (SAE).
* Model-Assisted (MA) - functions for integration with available Model-Assisted estimators.

**Analysis Tools**

* Analysis tools (an) - wrapper functions for stream-lining estimation processes.


### Overview of FIESTA spatial (sp) tools
FIESTA's spatial tools allow for summarizing and manipulating spatial data for use in FIESTA's estimation modules. 


FUNCTION  | DESCRIPTION
-------------- | ---------------------------------------------------------------
[spImportSpatial()](#spImportSpatial) | Imports a spatial layer to a sf object.
[spExportSpatial()](#spExportSpatial) | Exports a sf object to a spatial layer.
[spMakeSpatialPoints()](#spMakeSpatialPoints) | Generates an S4 SpatialPoints object from X/Y coordinates.
[spReprojectSpatial()](#spReprojectSpatial) | Reprojects a sf object.
[spClipPoint()](#spClipPoint) | Subset points with a Spatial polygon layer.
[spClipPoly()](#spClipPoly) | Subset Spatial polygons layer with another Spatial polygons layer.
[spClipRast()](#spClipRast) | Subset raster layer with a Spatial polygons layer.
[spExtractPoly()](#spExtractPoly) | Extracts point attribute values from Spatial polygons layer(s).
[spExtractRast()](#spExtractRast) | Extracts point attribute values from raster layer(s).
[spGetEstUnit()](#spGetEstUnit) | Extracts point attribute values and area for estimation unit(s).
[spGetStrata()](#spGetStrata) | Extracts point attribute values, area for estimation unit(s), and pixel counts for strata spatial layers.
[spUnionPoly()](#spUnionPoly) | Generates one Spatial polygons object from two Spatial polygons layers.
[spZonalRast()](#spZonalRast) | Extracts summary statistics by polygon (i.e., zone) for a raster.


### Objective of tutorial
The objective of this tutorial is to demonstrate how to use FIESTA's spatial tools for manipulating and summarizing spatial data. The examples use data from two inventory years of field measurements in the state of Wyoming, from FIADB_1.7.2.00, last updated June 20, 2018, downloaded on June 25, 2018 and stored as internal data objects in FIESTA.

## Example data - Wyoming (WY), Inventory Years 2011-2012

Data Frame | Description
-----------| --------------------------------------------------------------------------------
WYplt      | WY plot-level data
WYcond     | WY condition-level data
WYtree     | WY tree-level data

External data            | Description
-------------------------| ------------------------------------------------------------------
WYbighorn_adminbnd.shp   | Polygon shapefile of WY Bighorn National Forest Administrative boundary*
WYbighorn_districtbnd.shp| Polygon shapefile of WY Bighorn National Forest District boundaries**
WYbighorn_forest_nonforest_250m.tif| GeoTIFF raster of predicted forest/nonforest (1/0) for stratification*** 
WYbighorn_dem_250m.img   | Erdas Imagine raster of elevation change, in meters****


*USDA Forest Service, Automated Lands Program (ALP). 2018. S_USA.AdministrativeForest (\url{http://data.fs.usda.gov/geodata/edw}). Description: An area encompassing all the National Forest System lands administered by an administrative unit. The area encompasses private lands, other governmental agency lands, and may contain National Forest System lands within the proclaimed boundaries of another administrative unit. All National Forest System lands fall within one and only one Administrative Forest Area.

**USDA Forest Service, Automated Lands Program (ALP). 2018. S_USA.RangerDistrict (http://data.fs.usda.gov/geodata/edw). Description: A depiction of the boundary that encompasses a Ranger District.

***Based on MODIS-based classified map resampled from 250m to 500m resolution and reclassified from 3 to 2 classes: 1:forest; 2:nonforest. Projected in Albers Conical Equal Area, Datum NAD27 (Ruefenacht et al. 2008). Clipped to extent of WYbighorn_adminbnd.shp.

****USGS National Elevation Dataset (NED), resampled from 30m resolution to 250m. Projected in Albers Conical Equal Area, Datum NAD27 (U.S. Geological Survey 2017). Clipped to boundary of WYbighorn_adminbnd.shp.



### EXAMPLES

Set up for examples
```
# Load library
library(FIESTA)

## If not on windows platform, set up an outfolder to output from examples
if (.Platform$OS.type == "windows") {
  # Set workspace to FIESTA folder (create if doesn't exist)
  if (!file.exists("C:/FIESTA"))  {
    dir.create("C:/FIESTA")
  }
  setwd("C:/FIESTA")

  if (!file.exists("outfolder")) {
    dir.create("outfolder")
  }
  outfolder <- "outfolder"
}

# File names for external spatial data
WYbhfn <- system.file("extdata", "sp_data/WYbighorn_adminbnd.shp", package="FIESTA")
WYbhdistfn <- system.file("extdata", "sp_data/WYbighorn_districtbnd.shp", package="FIESTA")
WYbhdist.att <- "DISTRICTNA"

fornffn <- system.file("extdata", "sp_data/WYbighorn_forest_nonforest_250m.tif", package="FIESTA")
demfn <- system.file("extdata", "sp_data/WYbighorn_dem_250m.img", package="FIESTA")


# Other spatial layers used for examples, extracted using the raster package, getData function.
# County-level boundaries for USA and subset for Wyoming (Note: must have internet connection)
USAco <- raster::getData('GADM', country="USA", level=2)    
head(USAco@data)
WYco <- USAco[USAco$NAME_1 == "Wyoming",]



```


#### <a name="spImportShape"/>spImportShape()
```
###################################################################################
# Usage:
# spImportSpatial(layer = NULL, dsn = NULL, polyfix = FALSE, gui = FALSE) 
# 
# Description:
# Import a spatial layer (e.g., ESRI Shapefile) to a simple feature (sf) object.
###################################################################################

## Import external data shapefiles
WYbh <- FIESTA::spImportSpatial(WYbhfn)
WYbhdist <- FIESTA::spImportSpatial(WYbhdistfn)

## Display boundary
plot(sf::st_geometry(WYbhdist), border="blue")
plot(sf::st_geometry(WYbh), add=TRUE)


```


#### <a name="spExportSpatial"/>spExportSpatial()
```
###################################################################################
# Usage:
# spExportSpatial(sfobj, out_fmt = "shp", outfolder = NULL, out_dsn = NULL,   
#	      out_layer = NULL, outfn.pre = NULL, outfn.date = TRUE, overwrite_dsn = FALSE, 
#       overwrite_layer = NULL, append = FALSE) 
# 
# Description:
# Exports an sf object.
###################################################################################

## Export Spatial Polygons layer to a shapefile
FIESTA::spExportSpatial(WYbh, out_dsn="WYbh.shp", outfolder=outfolder, overwrite_dsn=TRUE)

## Check outfolder and display in ArcMap


```


#### <a name="spMakeSpatialPoints"/>spMakeSpatialPoints()
```
###################################################################################
# Usage:
# spMakeSpatialPoints(xyplt, xyplt_dsn = NULL, xy.uniqueid = NULL, 
#   xvar = NULL, yvar = NULL, xy.crs = 4269, prj = NULL, datum = NULL, zone = NULL,
# 	zoneS = FALSE, aea.param = "USGS", addxy = FALSE, exportsp = FALSE, ...) 
# 
# Description:
# Generates sf points object with defined projection.
###################################################################################

## Generate sf object from the WY plot data (x=LON_PUBLIC, y=LAT_PUBLIC) 
## Note: The coordinate reference system (crs) is: prj=longlat, datum=NAD83.

head(WYplt)
WYspplt <- FIESTA::spMakeSpatialPoints(xyplt=WYplt, xy.uniqueid="CN", xvar="LON_PUBLIC", 
        yvar="LAT_PUBLIC", prj="longlat", datum="NAD83")
WYspplt        
        
## ... or use EPSG code
WYspplt <- FIESTA::spMakeSpatialPoints(xyplt=WYplt, xy.uniqueid="CN", xvar="LON_PUBLIC", 
        yvar="LAT_PUBLIC", xy.crs=4269)
WYspplt 
        
        
        
## Display output
plot(sf::st_geometry(WYbhdist))
plot(sf::st_geometry(WYspplt), add=TRUE)

## NOTE: To display multiple layers, all layers must be in the same coordinate system.
lapply(list(WYbh, WYbhdist, WYspplt), sf::st_crs)

## Export spatial points to outfolder
WYspplt <- FIESTA::spMakeSpatialPoints(xyplt=WYplt, xy.uniqueid="CN", xvar="LON_PUBLIC", 
        yvar="LAT_PUBLIC", xy.crs=4269, exportsp=TRUE, out_dsn="spplt", out_fmt="shp",
        outfolder=outfolder, outfn.pre="WY", overwrite_layer=TRUE)


```

#### <a name="spReprojectVector"/>spReprojectVector()
```
###################################################################################
# Usage:
# spReprojectVector(layer, dsn = NULL, crs.new = NULL, prj.new = NULL, 
#     datum.new = NULL, ellps.new = NULL, zone.new = FALSE, 
#     zoneS.new = FALSE, aea.param.new = "USGS", exportsp = FALSE, ...) 
# 
# Description:
# Reprojects spatial vector layer. 
# NOTE: The layer must have a defined coordinate reference system. 
##      Test using sf::st_crs(x).
###################################################################################

## Reproject a vector Spatial object or file. 
sf::st_crs(WYspplt)
prj <- "+proj=utm +zone=12 +ellps=GRS80 +datum=NAD83 +units=m +no_defs"
WYspplt.utm12 <- FIESTA::spReprojectVector(layer=WYspplt, crs.new=prj)
        
## Check results
sf::st_crs(WYspplt.utm12)


```

#### <a name="spClipPoint"/>spClipPoint()
```
###################################################################################
# Usage:
# spClipPoint(xyplt, xyplt_dsn = NULL, xy.uniqueid = "PLT_CN", 
#     clippolyv, clippolyv_dsn = NULL, clippolyv.filter = NULL, showext = FALSE,  
#     keepNA = FALSE, savedata = FALSE, returnsp = TRUE, exportsp = FALSE, 
#     outfolder = NULL, out_fmt = "shp", out_dsn = NULL, out_layer = "pnt", 
#     outfn.pre = NULL, outfn.date = FALSE, overwrite = FALSE, 
#     othertabnms = NULL, ...) 
# 
# Description:
# Subset SpatialPoints or point file with a Spatial polygon boundary.
###################################################################################

## Get points within Bighorn National Forest boundary (project on the fly)
WYbhptslst <- FIESTA::spClipPoint(xyplt=WYplt, xy.uniqueid="CN", clippolyv=WYbh, 
    xvar="LON_PUBLIC", yvar="LAT_PUBLIC", prj="longlat", datum="NAD83")
names(WYbhptslst)
WYbhspplt <- WYbhptslst$clip_xyplt
WYbhprj <- WYbhptslst$clip_poly

## Check and display output
WYbhspplt
plot(sf::st_geometry(WYbhprj), border="red", lwd=2)
plot(sf::st_geometry(WYbhspplt), add=TRUE)


## NOTE: If the projection of spplt is not the same as the points layer, the  
##	 points layer will be reprojected to the same projection as clippolyv 
##   (See notes in help file for more info).


## Generate a sf object first, then clip sf points 
WYspplt <- FIESTA::spMakeSpatialPoints(xyplt=WYplt, xy.uniqueid="CN", xvar="LON_PUBLIC", 
        yvar="LAT_PUBLIC", xy.crs=4269)
WYbhptslst <- spClipPoint(xyplt=WYspplt, xy.uniqueid="CN", clippolyv=WYbh)


## Subset other tables with clipped points
WYbhptslst <- spClipPoint(xyplt=WYspplt, xy.uniqueid="CN", clippolyv=WYbh, 
        othertabnms=c("WYcond", "WYtree"))
names(WYbhptslst)


 
## Export clipped points
FIESTA::spExportSpatial(WYbhspplt, out_layer="WYbhpts", outfolder=outfolder, overwrite_layer=TRUE)


## Get points within Bighorn National Forest boundary (project on the fly)
## Save to outfolder
WYbhptslst <- FIESTA::spClipPoint(xyplt=WYplt, xy.uniqueid="CN", clippolyv=WYbh, 
    xvar="LON_PUBLIC", yvar="LAT_PUBLIC", prj="longlat", datum="NAD83",
    othertabnms=c("WYcond", "WYtree"), exportsp=TRUE, outfolder=outfolder, 
    overwrite=TRUE, outfn.pre="clip")
    
names(WYbhptslst)



```

#### <a name="spClipPoly"/>spClipPoly()
```
###################################################################################
# Usage:
# spClipPoly(polyv, polyv_dsn = NULL, clippolyv, clippolyv_dsn = NULL, 
#     clippolyv.filter = NULL, showext = FALSE, areacalc = FALSE, areaunits = "ACRES",  
#	    exportsp = FALSE, ...) 
# 
# Description:
# Clip (intersect) polygon vector layer with polygon vector layer.
###################################################################################


## Subset the USAco SpatialPolygons layer with WYbighorn
## NOTE: must download USAco from raster package. See above Example set up.
WYbhco <- FIESTA::spClipPoly(polyv=USAco, clippolyv=WYbh)

## Check and display WYbighorn_co with labels
head(WYbhco)
plot(sf::st_geometry(WYbhco['NAME_2']), col=sf.colors(nrow(WYbhco)))
coords <- st_coordinates(st_centroid(st_geometry(WYbhco)))
text(coords[,"X"], coords[,"Y"], WYbhco[["NAME_2"]])


```


#### <a name="spClipRast"/>spClipRast()
```
######################################################################################
# Usage:
# spClipRast(rast, rastfolder = NULL, clippolyv, clippolyv_dsn = NULL, 
#	    clippolyv.filter = NULL, rast.crs = NULL, bands = NULL, NODATA = NULL, 
#     buffdist = NULL, maskByPolygons = TRUE, showext = FALSE, setNODATA = FALSE, 
#     fmt = "HFA", outfolder = NULL, outfn = "rastclip", outfn.pre = NULL, 
#     outfn.date = FALSE, overwrite = FALSE)
# 
# Description:
# Subsets a raster to a polygon extent or boundary.
######################################################################################

## Subset the strata layer with the Medicine Wheel district boundary.
WYbhdist
WYbhMW <- WYbhdist[WYbhdist$DISTRICTNA == "Medicine Wheel Ranger District",]

plot(st_geometry(WYbhdist))
plot(st_geometry(WYbhMW), border="red", add=TRUE)

## Clip raster
WYbhMW.fornf <- FIESTA::spClipRast(fornffn, clippolyv=WYbhMW, outfolder=outfolder)

## NOTE: If the projection of polyv is not the same as rast, polyv will by reprojected
##	 to the same projection as rast before clipping (See note in help file for more details).


## Display results
WYbhMWprj <- FIESTA::crsCompare(WYbhMW, rasterInfo(WYbhMW.fornf)$crs)$x
raster::plot(raster::raster(WYbhMW.fornf))
plot(st_geometry(WYbhMWprj), border="red", add=TRUE)



```

#### <a name="spExtractPoly"/>spExtractPoly()
```
######################################################################################
# Usage:
# spExtractPoly(xyplt, xyplt_dsn = NULL, uniqueid = "PLT_CN", polyvlst,
#     polyv_dsn = NULL, polyvarlst = NULL, polyvarnmlst = NULL, keepNA = FALSE, 
#	    showext = FALSE, savedata = FALSE, exportsp = FALSE, exportNA = FALSE,
#     out_fmt = "shp", out_dsn = NULL, out_layer = "polyext", outfolder = NULL,
#	    outfn.pre = NULL, outfn.date = TRUE, overwrite = TRUE, ...) 
# 
# Description:
# Subset Spatial polygons layer with another Spatial polygons layer. 
######################################################################################

## Extract polygon attributes from WYbighorn to WYpts, keeping NULL values
extpolylst <- FIESTA::spExtractPoly(WYspplt, uniqueid="CN", polyvlst=WYbhdist)
WYspplt_bh <- extpolylst$sppltext

dim(WYspplt)
dim(WYspplt_bh)

head(WYspplt_bh)
plot(WYspplt_bh["DISTRICTNA"], pch=8)



## NOTE: If the projection of spplt is not the same as the Spatial Points, the Spatial 
##	 Points layer will be reprojected to the same projection as clippolyv before the 
##	 evaluation points (See note in help file for more details).


## Extract a subset of polygon attributes from WYbighorn to WYpts, not keeping NULL values
extpolylst <- FIESTA::spExtractPoly(WYspplt, uniqueid="CN", polyvlst=WYbh, 
          polyvarlst=c("FORESTNUMB", "FORESTNAME"), keepNA=FALSE)
WYspplt_bh2 <- extpolylst$sppltext

dim(WYspplt)
dim(WYspplt_bh2)

head(WYspplt_bh2)


```


#### <a name="spExtractRast"/>spExtractRast()
```
######################################################################################
# Usage:
# spExtractRast(xyplt, xyplt_dsn = NULL, uniqueid = "PLT_CN", rastlst, 
#     rastfolder = NULL, rast.crs = NULL, bandlst = NULL, var.name = NULL, 
#   	interpolate = FALSE, windowsize = 1, windowstat = NULL, rast.NODATA = NULL, 
#   	keepNA = TRUE, showext = FALSE, savedata = FALSE, exportsp =  FALSE, 
#   	exportNA = FALSE, outfolder = NULL, out_fmt = "shp", out_dsn = NULL, 
#     out_layer = "rastext", outfn.pre = NULL, outfn.date = TRUE, 
#     overwrite=FALSE, ...)
# 
# Description:
# Subset Spatial polygons layer with another Spatial polygons layer.
######################################################################################

## Extract raster values from WYdem to WYpts, not keeping NULL values
extrastlst <- FIESTA::spExtractRast(WYspplt, rastlst=c(fornffn, demfn), uniqueid="CN", keepNA=FALSE)
WYspplt_dem <- extrastlst$sppltext

dim(WYspplt)
dim(WYspplt_dem)

head(WYspplt_dem)


```

#### <a name="spGetPlots"/>spGetPlots()
```
######################################################################################
# Usage:
# spGetPlots(bnd, bnd_dsn = NULL, bnd.filter = NULL, states = NULL, stbnd = NULL, 
#	  stbnd_dsn = NULL, stbnd.att = NULL, RS = NULL, xy = NULL, xy_dsn = NULL, 
#   xy.uniqueid = "PLT_CN", xvar = "LON_PUBLIC", yvar = "LAT_PUBLIC", xy.crs = 4269, 
#	  clipxy = TRUE, datsource = "datamart", data_dsn = NULL, istree = TRUE, 
#	  isseed = FALSE, plot_layer= "plot", cond_layer = "cond", tree_layer = "tree", 
#   seed_layer = "seed", other_layers = NULL, puniqueid = "CN", evalid = NULL, 
#   evalCur = FALSE, evalEndyr = NULL, evalType = "VOL", measCur = FALSE, 
#   measEndyr = NULL, measEndyr.filter = NULL, invyrs = NULL, allyrs=FALSE,
#	  intensity1 = FALSE, showsteps = FALSE, savedata = FALSE, savebnd = FALSE, 
#	  savexy = FALSE, outfolder = NULL, out_fmt = "shp", out_dsn = NULL, outfn.pre = NULL, 
#	  outfn.date = FALSE, overwrite_dsn = FALSE, overwrite_layer = FALSE, ...)
# 
# Description:
# Extract data from FIA database for plots within a given boundary.
######################################################################################


## Extract public coordinates within WY Bighorn NF boundary
WYbhdat <- FIESTA::spGetPlots(bnd=WYbhfn, states="Wyoming", datsource="datamart", 
        evalCur=TRUE, istree=FALSE)
names(WYbhdat)


```


#### <a name="spGetModeldat"/>spGetModeldat()
```
######################################################################################
# Usage:
# spGetModeldat(xyplt = NULL, xyplt_dsn = NULL, uniqueid = "PLT_CN", 
#   domtype = "POLY", dom_layer = NULL, dom_dsn = NULL, domvar = "DOMAIN", 
#   rastlst.cont = NULL, rastlst.cont.name = NULL, rastlst.cont.stat = "MEAN", 
#   rastlst.cont.NODATA = NULL, rastlst.cat = NULL, rastlst.cat.name = NULL,
#	  rastlst.cat.NODATA = NULL, rastfolder = NULL,  
#   asptransform = FALSE, rast.asp = NULL, rast.lut = NULL, rastlut = NULL, 
#   areacalc = TRUE, areaunits = "ACRES", keepNA = TRUE, NAto0 = FALSE,
#   showext = TRUE, savedata = FALSE, exportsp = FALSE, exportNA = FALSE,
#   outfolder = NULL, out_fmt = "csv", out_dsn = NULL, outfn.pre = NULL,
#   outfn.date = TRUE, overwrite = FALSE, vars2keep = NULL, ...) 
# 
# Description:
# Get data extraction and zonal statistics for Model-assisted or
#		Model-based (Small Area) Estimation. The major steps are as follows:
#   1) Check parameters 
#   2) Extract point values from domlayer
#   3) Set up output data structures
#   4) Extract point values and get zonal statistics from continuous raster layers
#   5) Extract point values and get zonal statistics from categorical raster layers
#   6) Get total acres from domlayer (if areacalc=TRUE)
######################################################################################

## Generate a sf object from the WY plot data, public coordinates 
## (x=LON_PUBLIC, y=LAT_PUBLIC) 
## Note: The public coordinate projection information is: prj=longlat, datum=NAD83.
WYspplt <- FIESTA::spMakeSpatialPoints(xyplt=WYplt, xy.uniqueid="CN", xvar="LON_PUBLIC", 
        yvar="LAT_PUBLIC", xy.crs=4269)
        
## Derive new layers from dem
library(raster)
dem <- raster(demfn)
slp <- raster::terrain(dem, opt="slope", unit="degrees", 
  filename=paste0(outfolder, "/WYbh_slp.img"), overwrite=TRUE)
asp <- raster::terrain(dem, opt="aspect", unit="degrees", 
  filename=paste0(outfolder, "/WYbh_asp.img"), overwrite=TRUE)


## Extract estimation unit and zonal raster statistics (i.e., mean) 
rastlst.cont <- c(demfn, slp, asp)
rastlst.cont.name <- c("dem", "slp", "asp")
rastlst.cat <- fornffn
rastlst.cat.name="fornf"

modeldat <- FIESTA::spGetModeldat(xyplt=WYspplt, uniqueid="CN", dom_layer=WYbhfn, 
  domvar=NULL, rastlst.cont=rastlst.cont, rastlst.cont.name=rastlst.cont.name, 
  rastlst.cat=rastlst.cat, rastlst.cat.name=rastlst.cat.name, rastlst.cont.stat="mean",
  asptransform=TRUE, rast.asp=asp, keepNA=FALSE, showext=FALSE, 
  savedata=FALSE)
names(modeldat)

pltassgn <- modeldat$pltassgn
unitmodel <- modeldat$domzonal
unitvar <- modeldat$domvar
inputdf <- modeldat$inputdf
unitarea <- modeldat$domarea
areavar <- modeldat$areavar
inputdf <- modeldat$inputdf
prednames <- modeldat$prednames
zonalnames <- modeldat$zonalnames

unitvar
areavar
unitmodel
unitarea
head(pltassgn)

prednames
zonalnames


```



#### <a name="spGetEstUnit"/>spGetEstUnit()
```
######################################################################################
# Usage:
# spGetEstUnit(xyplt, xyplt_dsn = NULL, uniqueid = "PLT_CN", unittype = "POLY", 
#   	unit_layer = NULL, unit_dsn = NULL, unitvar = NULL, unit.filter = NULL, 
#     areavar = NULL, areaunits = "ACRES", rast.NODATA = NULL, keepNA = FALSE,  
#     showext = TRUE, savedata = FALSE, exportsp = FALSE, exportNA = FALSE,  
#     outfolder = NULL, out_fmt = "shp", out_dsn = NULL, out_layer = "unit_assgn", 
#     outfn.date = TRUE, outfn.pre = NULL, overwrite = FALSE, ...) 
# 
# Description:
# Extract estimation unit values to plots and calculate area by estimation unit.
######################################################################################

## Create spatial points from WYplt
WYspplt <- spMakeSpatialPoints(xyplt=WYplt, xy.uniqueid="CN", xvar="LON_PUBLIC", 
        yvar="LAT_PUBLIC", xy.crs=4269)
xyplt=WYspplt


## By Bighorn National Forest ##
# Get estimation unit acres for Bighorn National Forest.
######################################################################################
unitdat.bh <- spGetEstUnit(xyplt=WYplt, uniqueid="CN", xvar="LON_PUBLIC", yvar="LAT_PUBLIC", 
    xy.crs=4269, unit_layer=WYbhfn)

names(unitdat.bh)
sppltunit.bh <- unitdat.bh$sppltassgn
unitarea.bh <- unitdat.bh$unitarea
unitvar.bh <- unitdat.bh$unitvar
areavar.bh <- unitdat.bh$areavar

unitarea.bh
unitvar.bh
areavar.bh


## By Bighorn National Forest District ##
# Get estimation unit acres and strata information for Bighorn National Forest.
######################################################################################
unitdat.bhdist <- spGetEstUnit(xyplt=WYplt, uniqueid="CN", xvar="LON_PUBLIC", yvar="LAT_PUBLIC", 
    xy.crs=4269, unit_layer=WYbhdistfn, unitvar="DISTRICTNA")

names(unitdat.bhdist)
sppltunit.bhdist <- unitdat.bhdist$sppltassgn
unitarea.bhdist <- unitdat.bhdist$unitarea
unitvar.bhdist <- unitdat.bhdist$unitvar
areavar.bhdist <- unitdat.bhdist$areavar

unitarea.bhdist
unitvar.bhdist
areavar.bhdist


```


#### <a name="spGetStrata"/>spGetStrata()
```
######################################################################################
# Usage:
# spGetStrata(xyplt, xyplt_dsn = NULL, uniqueid = "PLT_CN", unittype = "POLY",
#     unit_layer = NULL, unit_dsn = NULL, unitvar = NULL, unit.filter = NULL, 
#     strattype = "RASTER", strat_layer = NULL, strat_dsn = NULL, strvar = NULL, 
#   	strat_lut = NULL, areaunits = "ACRES", rast.NODATA = NULL, keepNA = FALSE, 
#     showext = TRUE, savedata = FALSE, exportsp = FALSE, exportNA = FALSE, 
#     outfolder = NULL, out_fmt = "shp", out_dsn = NULL, out_layer = "strat_assgn", 
#     outfn.date = TRUE, outfn.pre = NULL, overwrite = FALSE, ...) 
# 
# Description:
# Wrapper to extract attribute and area from a polygon or raster estimation 
#	unit laer and a polygon or raster layer with strata pixel categories.
######################################################################################

## Generate a sf object from the WY plot data, public coordinates 
## (x=LON_PUBLIC, y=LAT_PUBLIC) 
## Note: The public coordinate projection information is: prj=longlat, datum=NAD83.
WYspplt <- FIESTA::spMakeSpatialPoints(xyplt=WYplt, xy.uniqueid="CN", xvar="LON_PUBLIC", 
        yvar="LAT_PUBLIC", xy.crs=4269)

## Extract polygon attributes from WYbighorn to WYpts, keeping NULL values
stratlst <- FIESTA::spGetStrata(WYspplt, uniqueid="CN", unittype="POLY", unit_layer=WYbhfn,
     strattype="RASTER", strat_layer=fornffn) 
names(stratlst) 

pltassgn <- stratlst$pltassgn
unitarea <- stratlst$unitarea
stratalut <- stratlst$stratalut

head(pltassgn)
unitarea
head(stratalut)
stratlst$strvar
stratlst$unitvar


```

#### <a name="spUnionPoly"/>spUnionPoly()
```
######################################################################################
# Usage:
# spUnionPoly(polyv1, polyv1_dsn = NULL, polyv2, polyv2_dsn = NULL, showext = TRUE,
#     areacalc = FALSE, areavar = "ACRES_GIS", exportsp = FALSE, ...)
# 
# Description:
# Generate a unioned sf object with polygons and attribtutes from two sf polygon objects..
######################################################################################
WYbh <- FIESTA::spImportSpatial(WYbhfn)

## Extract polygon attributes from WYbighorn to WYpts, keeping NULL values
polyUnion <- FIESTA::spUnionPoly(polyv1=USAco[USAco$NAME_1 == "Wyoming",], polyv2=WYbh, 
      areacalc=TRUE)

plot(st_geometry(polyUnion))
head(polyUnion)


```

#### <a name="spZonalRast"/>spZonalRast()
```
######################################################################################
# Usage:
# spZonalRast(polyv, polyv_dsn = NULL, polyv.att = NULL, rast, rastfolder = NULL, 
#     polyatt = NULL, bands = NULL, zonalstat = NULL, pixelfun = NULL, outname = NULL, 
#     showext = FALSE, rastlut = NULL, rast.NODATA = NULL, na.rm = TRUE, 
#     savedata = FALSE, outfolder = NULL, outfn = "zonalext", outfn.pre = NULL, 
#     outfn.date = FALSE, overwrite = FALSE) 
# 
# Description:
# Extracts summary statistics by polygon (i.e., zone).
######################################################################################
WYbhdist <- FIESTA::spImportSpatial(WYbhdistfn)

## Extract polygon attributes from WYbighorn to WYpts, keeping NULL values
zonallst <- FIESTA::spZonalRast(polyv=WYbhdist, polyv.att="DISTRICTNA", rastfn=demfn, 
      zonalstat=c("mean", "sum")) 
names(zonallst) 

zonalext <- zonallst$zonalext
outname <- zonallst$outname
rasterfile <- zonallst$rasterfile

head(zonalext)
outname
rasterfile


```
