---
title: "FIESTA - Database Tools"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{FIESTA - Database Tools}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---


## FIESTA Overview
The R package, FIESTA (Forest Inventory ESTimation and Analysis) is a research estimation tool for analysts that work with sample-based inventory data from the U.S. Department of Agriculture, Forest Service, Forest Inventory and Analysis (FIA) Program to accommodate: unique population boundaries, different evaluation time periods, customized stratification schemes, non-standard variance equations, integration of multi-scale remotely-sensed data and other auxiliary information, and interaction with other modeling and estimation tools from CRAN R's library of packages. FIESTA contains a collection of functions that can access FIA databases, summarize and compile plot and spatial data, and generate estimates with associated sampling errors. 


Functions are organized by type or objective and are named with a corresponding prefix: 

* Database tools (DB) - functions for querying and extracting data from FIA's national database.

* Data tools (dat) - functions for summarizing and exploring FIA data.

* Spatial tools (sp) - functions for manipulating and summarizing spatial data.

* Estimation modules (GB, PB, SA) - functions for different estimation strategies, such as FIA's standard 'Green-Book' estimators (GB); suplementary photo-based estimators (PB); integration with different available small area estimators (SAE) or other model-assisted or model-based estimation tools, such as LASSO.

* Analysis tools (an) - wrapper functions for steam-lining estimation processes.



FIESTA's DB tools extract data from FIA's online publically-available comma-delimited files (\*.csv or \*.zip). FIA's CSV files are available by state from the FIA DataMart at the following link: https://apps.fs.usda.gov/fia/datamart/datamart.html. Because of FIA's confidentiality agreement to protect the privacy of landowners, as well as protecting the scientific integrity of FIA's sample design, the exact coordinates of the sample plot locations are not included in the public data. If the exact coordinates are necessary for your analysis, contact FIA's Spatial Data Services (https://www.fia.fs.fed.us/tools-data/spatial/index.php).


### Objective of tutorial
The objective of this tutorial is to demonstrate the use of FIESTA's DB tools for accessing FIA data. These tools extract data from FIAD Datamart using FIA's standard evaluations as well as customized evaluations (DBgetPlots and DBgetStrata). An FIA Evaluation is a group of plots within the FIA database that is used for population estimates. An FIA Evaluation represents different inventory spans of data with different stratification and area adjustments for nonreponse. Each Evaluation is determined by the type of estimation (evalType) including: area and tree estimates, growth and mortality estimates, and area change estimates (evalType). These plots are identified by an evalid, which is a unique identifier in the format of a 2-digit State code, a 2-digit year code, and a 2-digit evaluation type code. For example, EVALID '491601' represents the Utah 2016 evaluation for current area estimates. 

FUNCTION  | DESCRIPTION
-------------- | ---------------------------------------------------------------
[DBgetCSV()](#DBgetCSV) | Downloads comma-delimited file (.csv) or downloads and extracts a compressed csv file (.zip) from FIA's online DataMart.
[DBqryCSV()](#DBqryCSV) | Extracts and queries data from FIA's online DataMart, either CSV or ZIP files.
[DBgetEvalid()](#DBgetEvalid) | Gets evalid for identifying an estimation group of plots for state or checks evalid.
[DBgetPlots()](#DBgetPlots) | Extracts inventory plot data from FIA database.
[DBgetStrata()](#DBgetStrata) | Extracts strata information and total acres by estimation unit from FIA database, including plot-level assignment and a data frame with strata weights by estimation unit.


### EXAMPLES

Set up for examples
```
# Load library
library(FIESTA)

# Set workspace to FIESTA folder (create if doesn't exist)
if (!file.exists("C:/FIESTA"))  dir.create("C:/FIESTA")
setwd("C:/FIESTA")

# Create 2 subfolders under the FIESTA folder, 'data' and 'outfolder' and set path to objects 
if (!file.exists("data"))  dir.create("data")
datfolder <- "data" 

if (!file.exists("outfolder")) dir.create("outfolder")
outfolder <- "outfolder"


## Load SQLite database from FIESTAdata package
WYdat <- system.file("extdata", "WYdat_eval2013.sqlite", package="FIESTA")


```

The following examples show how to use FIA's publically-available, online zipfiles or a custom-built SQLite database that is stored internal to FIESTA. The plot coordinates have been altered for privacy (See https://www.fia.fs.fed.us/tools-data/spatial/Policy/index.php for details). The zip files are extracted on-the-fly from the online website. Web server connections will affect download speeds.



#### <a name="DBgetCSV"/>DBgetCSV()
```
####################################################################################
# Usage:
# DBgetCSV(DBtable, states = NULL, ZIP = TRUE, returnDT = TRUE) 
# 
# Description:
# Downloads *.csv file or downloads and extracts a *.zip file from FIA DataMart.
# Only 1 table can be specified, but multiple states may be included.
# Value:
# Returns a data table (returnDT=TRUE), or data.frame (returnDT=FALSE).
####################################################################################

## Get plot table for Wyoming
WYplots <- DBgetCSV("PLOT", "Wyoming")
dim(WYplots)

## Get plot table for Wyoming and Utah
WYUTplots <- DBgetCSV(DBtable="PLOT", states=c("Wyoming", "Utah"))
table(WYUTplots$STATECD)

## Get survey table for Wyoming
WYsurvey <- DBgetCSV("SURVEY", "Wyoming")
WYsurvey

## Get ref_unit table
ref_research_station <- DBgetCSV("ref_research_station")
head(ref_research_station)


```


#### <a name="DBqryCSV"/>DBqryCSV()
```
####################################################################################
# Usage:
# DBqryCSV(sql, ZIP = TRUE, states = NULL, sqltables = NULL) 
# 
# Description:
# Queries and extracts data from FIA's online data sources (FIA DataMart), 
#	either CSV or ZIP files (Note: must use SQL syntax).
#
# Value:
# Returns a data frame from resulting query.
####################################################################################

# QUERY1: Number of plots by inventory year for the state of Wyoming
sql1.csv <- "select INVYR, count(*) AS NBRPLOTS 
          from plot 
          where statecd=56 group by INVYR"
DBqryCSV(sql=sql1.csv, states="Wyoming", sqltables="plot")

# QUERY2: min, mean, max height by FORTYPCD in Wyoming
sql2b.csv <- "select c.FORTYPCD, min(HT) HTmin, round(avg(HT)) HTmean, max(HT) maxHT 
			        from cond c INNER JOIN tree t ON c.PLT_CN = t.PLT_CN 
			        where c.statecd = 56 
			        group by c.FORTYPCD order by c.FORTYPCD"
DBqryCSV(sql=sql2b.csv, states="Wyoming", sqltables=c("cond", "tree"))

# QUERY3: Number of plots by inventory year for Utah and Wyoming
sql3.csv <- "select STATECD, INVYR, count(*) NBRPLOTS 
          from plot 
          where statecd in(49,56) group by STATECD, INVYR"
DBqryCSV(sql=sql3.csv, states=c("Utah", "Wyoming"), sqltables="plot")


```


#### <a name="DBgetEvalid"/>DBgetEvalid()
```
######################################################################################
# Usage:
# DBgetEvalid(states = NULL, RS = NULL, datsource = "CSV", ZIP = TRUE, FS_FIADB = TRUE,  
#   invyrtab = NULL, invtype = "ANNUAL", evalCur = TRUE, evalEndyr = NULL, evalid = NULL, 
#   evalType = "ALL", dbconn = NULL, dbconnopen = FALSE, gui = FALSE)
# 
# Description:
# Extracts an evalid for identifying an estimation group of plots. If evalCur=TRUE, 
#	extracts current evalid and inventory years for state(s), or for a specified 
#	evalEndyr. Otherwise checks an evalid and returns states and inventory years.
#
# Value:
# A list of data objects:
#   $states      - state names
#   $rslst       - FIA research station names included in output
#   $evalidlist  - evalid by state
#   $invtype     - inventory type for state(s) (ANNUAL/PERIODIC)
#   $invyrtab    - a data frame with inventory years by state corresponding to evalid
#   $evalType    - Evaluation type(s) included in query
#   $invyrs      - a list of inventory years by state corresponding to evalid
######################################################################################

help(DBgetEvalid)

# Using GUI interface. 
eval <- DBgetEvalid()
names(eval)
eval

## Get evalid and inventory years for Wyoming
WYeval <- DBgetEvalid(states="Wyoming")
names(WYeval)
WYeval$evalidlist
WYeval$invyrs
WYeval$invyrtab
WYeval$invtype

## Get evalids for Utah and Wyoming
UTWYeval <- DBgetEvalid(states=c("Wyoming", "Utah"))
UTWYeval$evalidlist
UTWYeval$invyrs
UTWYeval$invyrtab
UTWYeval$invtype

## Get most current evaluation for all states in RMRS and NCRS FIA research units
eval.cur <- DBgetEvalid(RS=c("RMRS", "NCRS"), evalCur=TRUE)
names(eval.cur)
eval.cur$evalidlist

## Get most current evaluation for New York and Texas for areavol and grm evalTypes
NYTXeval.cur <- DBgetEvalid(states=c("New York", "Texas"), evalType=c("AREAVOL", "GRM"))
names(NYTXeval.cur)
NYTXeval.cur$evalidlist
NYTXeval.cur$evalTypelist


```

#### <a name="DBgetPlots"/>DBgetPlots()
```
######################################################################################
# Usage:
# DBgetPlots(states = NULL, RS = NULL, invtype = "ANNUAL", evalid = NULL, 
#   evalCur = FALSE, evalEndyr = NULL, evalType = "AREAVOL", measCur = FALSE, 
#   measEndyr = NULL, allyrs = FALSE, invyrs = NULL, istree = FALSE, isseed = FALSE, 
#   isveg = FALSE, othertables = NULL, issp = FALSE, spcond = FALSE,
#   spcondid1 = FALSE, defaultVars = TRUE, regionVars = FALSE, ACI = FALSE,
#   subcycle99 = FALSE, intensity1 = TRUE, stateFilter = NULL, allFilter = NULL,  
#   savedata = FALSE, parameters = FALSE, outfolder = NULL, outSQLitefn = NULL,
#   gpkg = FALSE, outfn.pre = NULL, outfn.date = FALSE, overwrite = FALSE, 
#   savePOP = FALSE)
# 
# Description:
# Extracts field, calculated, and derived data from FIA's publically-accessible 
#   online DataMart (https://apps.fs.usda.gov/fia/datamart/datamart.html).
# 
# Value:
# A list of data objects:
#   $states   - state names
#   $plt		  - Plot variables from PLOT table
#   $cond		  - Cond variables from COND table
#   $tree		  - If istree=TRUE, tree variables from TREE table
#   $seed 		- If isseed=TRUE, seedling variables from SEEDLING table
#   $spplt_*	- if issp=TRUE, SpatialPoints object with plot and some cond attributes  
#              represented at plot-level (see help for details).
#   $vspspp  - if isveg=TRUE, subplot understory vegetation from P2VEG_SUBPLOT_SPP
#   $vspstr  - if isveg=TRUE, subplot cover and layer understory vegetation from P2VEG_SUBP_STRUCTURE
#   $evalid  - if evalCur=TRUE or evalEndyr is not NULL, evalidation ID by state
#   $pltcnt  - number of plots by state, cycle, inventory year, and plot status
#
# If savedata=TRUE:
#	- If saveqry=TRUE, text file(s) of SQL queries used to extract data from database (*.txt),
#		Note: the plot and cond table is 1 query (pltcondqry*.txt).
#	- If parameters=TRUE, text file of parameters used. This file can be used to run program again 
#   (DBgetPlots_parameters_'date'.txt).
#	- If text file of plot and condition counts (pltcnt_*'date'.txt).
#	- If comma-delimited files of data frame objects (*'date'.csv).
#	- If issp=TRUE, an ESRI shapefile of plot and some condition attributes (shp_PUBLIC_'date'.shp).
#   Variable names are truncated to 10 characters or less. 
#	- If issp=TRUE, a comma-delimited file of the SpatialPoints data frame (shpdat_PUBLIC_'date'.csv).
#	- If issp=TRUE, a comma-delimited file of truncated names for conversion to shapefile
#   (shp_PUBLIC_newnames_'date'.shp). See notes for more info.
######################################################################################

help(DBgetPlots)

source("C:\\_tsf\\_GitHub\\FIESTA\\R\\DBgetPlots.R")
# Using GUI interface.
dat <- DBgetPlots()
names(dat)
save(dat, file=paste(outfolder, "dat.rda"), sep="/")


# Most current evaluation and shapefile with public coordinates
WYdat1 <- DBgetPlots(states="Wyoming", evalCur=TRUE, issp=TRUE)
names(WYdat1)
WYplt1 <- WYdat1$plt
WYcond1 <- WYdat1$cond
WYspxy_PUBLIC1 <- WYdat1$spxy_PUBLIC
WYdat1$evalid
WYdat1$pltcnt

dim(WYplt1)

# Look at output
head(WYcond1)
plot(st_geometry(WYspxy_PUBLIC1))
table(WYplt1$INVYR)


# Add stateFilter (NOTE: only plot-level filters)
WYdat1b <- DBgetPlots(states="Wyoming", evalCur=TRUE, issp=TRUE, stateFilter="p.COUNTYCD == 1")
dim(WYdat1b$plt)



# Include tree data
WYdat1 <- DBgetPlots(states="Wyoming", evalCur=TRUE, issp=TRUE, istree=TRUE)
names(WYdat1)
WYtree1 <- WYdat1$tree
head(WYtree1)

## Save to SQLite database ("C:/FIESTA/data.sqlite")
WYdat1 <- DBgetPlots(states="Wyoming", evalCur=TRUE, issp=TRUE, istree=FALSE,
              savedata=TRUE, outfolder=outfolder, 
              out_fmt="sqlite", out_dsn="data6.sqlite", overwrite=TRUE, othertables="SUBPLOT")

sqlitefn <- file.path(outfolder, "data6.sqlite")

## Connect to database and list tables
conn <- DBI::dbConnect(RSQLite::SQLite(), sqlitefn)
DBI::dbListTables(conn)
sf::st_layers(sqlitefn)

## Read in plot table
plt <- DBI::dbReadTable(conn, "plot")
dim(plt)

## Read in spatial xy coordinates
spxy_public <- sf::st_read(sqlitefn, layer="spxy_public")
dim(spxy_public)

plot(sf::st_geometry(spxy_public))


# Most current evaluation and shapefile with public coordinates, 
# evalTypes - all, areavol, and growmort
##################################################################################
WYdat1a <- DBgetPlots(states="Wyoming", evalCur=TRUE, issp=TRUE, 
                    evalType=c("ALL", "AREAVOL", "GRM"))
names(WYdat1a)
WYplt1a <- WYdat1a$plt
WYcond1a <- WYdat1a$cond
WYdat1a$evalid

# Look at output
dim(WYplt1a)
head(WYplt1a)
table(WYplt1a$EVALID)


## Get WYplt, evalid ending in 00 
WYplt00 <- WYplt1a[endsWith(as.character(WYplt1a$EVALID), "00"),]
dim(WYplt00)


# Inventory years 2012:2014 and shapefile with public coordinates
##################################################################################
WYdat2 <- DBgetPlots(states="Wyoming", invyrs=2012:2014, issp=TRUE)
names(WYdat2)
WYplt2 <- WYdat2$plt
WYcond2 <- WYdat2$cond
WYspplt_PUBLIC2 <- WYdat2$spxy_PUBLIC
WYdat2$pltcnt

# Look at output
head(WYcond2)
plot(sf::st_geometry(WYspplt_PUBLIC2))
table(WYplt2$INVYR)


# Two different states, most current evaluation
##################################################################################
UTWYdata <- DBgetPlots(states=c("Utah", "Wyoming"), evalCur=TRUE)
names(UTWYdata)
UTWYdata$pltcnt
UTWYplt <- UTWYdata$plt
table(UTWYplt$STATECD, UTWYplt$INVYR)


# Two different states, one inventory year
##################################################################################
UTWY15data <- DBgetPlots(states=c("Utah", "Wyoming"), invyrs=2015)
names(UTWY15data)
UTWY15data$pltcnt
UTWY15plt <- UTWY15data$plt
table(UTWY15plt$STATECD, UTWY15plt$INVYR)


# Two different states, different inventory years
##################################################################################
UTWYdata2 <- DBgetPlots(states=c("Utah", "Wyoming"), invyrs=list(Utah=2010, Wyoming=2015))
names(UTWYdata2)
UTWYdata2$pltcnt


# All years of periodic data for Wyoming
##################################################################################
WYdata.periodic <- DBgetPlots(states="Wyoming", invtype="PERIODIC", 
    allyrs=TRUE)
names(WYdata.periodic)
WYdata.periodic$pltcnt


# Most current evaluation of periodic data for Wyoming
# Note: the periodic inventory did not have evalType="ALL"
##################################################################################
WYdata.periodic2 <- DBgetPlots(states="Wyoming", invtype="PERIODIC", evalCur=TRUE,
      evalType="AREAVOL")
names(WYdata.periodic2)
WYdata.periodic2$pltcnt


# Most current evaluation of Utah and Wyoming filtered for OWNCD=11
##################################################################################
UTWYdata.nfs <- DBgetPlots(states=c("Utah", "Wyoming"), evalEndyr=2017, 
                  allFilter="OWNCD == 11", evalType="ALL")
names(UTWYdata.nfs)
UTWYdata.nfs$pltcnt
table(UTWYdata.nfs$cond$ADFORCD)


# Most current inventory years for Idaho/Montana, R1, filtered for OWNGRPCD=10
# Include tree data
##################################################################################
UTdata.nfs <- DBgetPlots(states=c("Idaho", "Montana"), invyrs=2008:2017, istree=TRUE,
                  allFilter="OWNGRPCD == 10 & (ADFORCD > 100 & ADFORCD < 200)")
names(UTdata.nfs)
UTdata.nfs$pltcnt
table(UTdata.nfs$cond$ADFORCD)



################## All Condition Inventory (ACI) data

# Region 1 plots, filtered for OWNGRPCD=10, include tree data with ACI
# Note: ACI data are not included in FIA evaluations, must specify inventory years
##################################################################################
UTdata.nfsACI <- DBgetPlots(states=c("Idaho", "Montana"), invyrs=2008:2017, 
                  istree=TRUE, ACI=TRUE, 
                  allFilter="OWNGRPCD == 10 & (ADFORCD > 100 & ADFORCD < 200)")
names(UTdata.nfsACI)
UTdata.nfsACI$pltcnt
table(UTdata.nfsACI$cond$ADFORCD)



## Compare with FIA 2008-2017 Inventory years, not including ACI data
table(UTdata.nfs$plt$NF_PLOT_STATUS_CD)
dim(UTdata.nfs$tree)

table(UTdata.nfsACI$plt$NF_PLOT_STATUS_CD)
dim(UTdata.nfsACI$tree)



# All inventory years for Utah
##################################################################################
UTdat.all <- DBgetPlots(states="Utah", allyrs=TRUE)
names(UTdat.all)
UTplt.all <- UTdat.all$plt
table(UTplt.all$INVYR)



################## Save to SQLite database

# Wyoming - most current evaluation - save to SQLite database
##################################################################################
WYdat <- DBgetPlots(states="Wyoming", evalCur=TRUE, istree=TRUE, 
          savedata=TRUE, outfolder=outfolder, outSQLitefn="WYdat",
          overwrite=TRUE)
names(WYdat)
WYplt <- WYdat$plt
WYcond <- WYdat$cond
WYtree <- WYdat$tree
WYpltcnt <- WYdat$pltcnt

head(WYplt)
head(WYcond)
head(WYtree)
WYpltcnt

## Read SQLite database
dsn <- file.path(outfolder, "WYdat.sqlite")
conn <- dbConnect(RSQLite::SQLite(), dsn)
dbListTables(conn)
WYplt <- dbGetQuery(conn, "select * from plot")
dbDisconnect(conn)


```

#### <a name="DBgetStrata"/>DBgetStrata()
```
######################################################################################
# Usage:
# DBgetStrata(dat = NULL, uniqueid = "CN", states = NULL, evalid = NULL, 
#   evalCur = FALSE, evalEndyr = NULL, evalType = "AREAVOL", savedata = FALSE, 
#   outfolder = NULL, outfn.pre = NULL, outfn.date = FALSE, overwrite = FALSE, 
#   POP_PLOT_STRATUM_ASSGN = NULL)
# 
# Description:
# Gets strata information from FIA DataMart, including:
# (1) strata and estimation unit assignment per plot; (2) total area by estimation unit;
# (3) pixel counts and number plots by strata/estimation unit. 
# 
# Value:
# A list of data objects:
#   $pltassgn    - plot-level strata/estimation unit assignment
#   $pltassgnid  - name of unique identifier for plot in pltassgn
#   $unitarea    - total acres by estimation unit
#   $unitvar     - name of estimation unit variable (ESTN_UNIT)
#   $areavar     - name acre variable (ACRES)
#   $strlut      - strata look-up table with summarized pixel counts (P1POINTCNT)
#   $strvar      - name of strata variable (STRATA)
#   $strwtvar    - name of strata weight variable (P1POINTCNT)
#   $evalid      - the evalid used
#
# If savedata=TRUE:
#	- Comma-delimited file of datstrat (*'date'.csv).
#	- Comma-delimited file of unitarea (*'date'.csv).
#	- Comma-delimited file of stratalut (*'date'.csv).
#	- If collapsed, a comma-delimited file of original classes and new collapsed classes.
######################################################################################

help(DBgetStrata)


## From CSV files ##
# Get strata for the most current evaluation for Wyoming
WYstrat1 <- DBgetStrata(states="Wyoming", evalCur=TRUE)
names(WYstrat1)

WYpltassgn <- WYstrat1$pltassgn
head(WYpltassgn)
WYstrat1$unitarea
WYstrat1$unitvar
WYstrat1$areavar
WYstrat1$strlut
WYstrat1$strvar
WYstrat1$strwtvar
WYstrat1$evalid


# Get strata information for a specific evaluation for Wyoming
WYstrat2 <- DBgetStrata(evalid=561200, savedata=TRUE, outfolder=outfolder)
names(WYstrat2)
WYpltassgn2 <- WYstrat2$pltassgn
head(WYpltassgn2)
WYstrat2$unitarea
WYstrat2$strlut
WYstrat2$strwtvar
WYstrat2$evalid


# Get strata information for Wyoming, evaluation ending in 2014
WYstrat3 <- DBgetStrata(states="Wyoming", evalEndyr=2014)
names(WYstrat3)
WYpltassgn3 <- WYstrat3$pltassgn
head(WYpltassgn3)
WYstrat3$unitarea
WYstrat3$strlut
WYstrat3$strwtvar
WYstrat3$evalid


# Get strata information for a specific set of Wyoming plots
WYstrat4 <- DBgetStrata(dat=WYplt)
names(WYstrat4)
WYpltassgn4 <- WYstrat4$pltassgn
head(WYpltassgn4)
WYstrat4$unitarea
WYstrat4$strlut
WYstrat4$evalid


## Get strata information for Wyoming plots, 1 inventory year
WY2013strat <- DBgetStrata(dat=WYplt[WYplt$INVYR == 2013, ])
names(WY2013strat)
WY2013pltassgn <- WY2013strat$pltassgn
head(WY2013pltassgn)
WY2013strat$unitarea
WY2013strat$strlut
WY2013strat$strwtvar
WY2013strat$evalid


## Get strata information for Utah and Wyoming, most current evaluations
UTWYstrat <- DBgetStrata(states=c("Utah", "Wyoming"), evalCur=TRUE)
names(UTWYstrat)
UTWYpltassgn <- UTWYstrat$pltassgn
table(UTWYpltassgn$STATECD)
UTWYstrat$unitarea
UTWYstrat$strlut
UTWYstrat$evalid


## Get strata information for Utah, evalid 491500 and Wyoming, evalid 561500
UTWYstrat2 <- DBgetStrata(evalid = list(Utah=491500, Wyoming=561500))
names(UTWYstrat2)
UTWYpltassgn2 <- UTWYstrat2$pltassgn
table(UTWYpltassgn2$STATECD)
UTWYstrat2$unitarea
UTWYstrat2$strlut
UTWYstrat2$strwtvar
UTWYstrat2$evalid


## Get strata information all inventory years of Utah
## Note: For plots locations that have been visited more than once: all 
#   plots are assigned an estimation unit and strata value, but area and 
#   strata proportions are from the most current evaluation.
UTdat.all <- DBgetPlots(states="Utah", allyrs=TRUE)
names(UTdat.all)
UTplt.all <- UTdat.all$plt
table(UTplt.all$INVYR)

UTstrat.all <- DBgetStrata(dat=UTplt.all, evalType="ALL")
names(UTstrat.all)
dim(UTplt.all)
pltassgn <- UTstrat.all$pltassgn
dim(pltassgn)

UTstrat.all$unitarea
UTstrat.all$strlut


```

