---
title: "A report for `r params$AOInm`"
output:
  word_document:
    reference_docx: template.docx
params:
  rawfolder: ""
  AOInm: ""
  title.ref: NULL
  year: NULL
  GBpopdat: NULL
---


```{r echo=FALSE, warning=FALSE, message=FALSE}
library(FIESTA)

#rawfolder <- "C:/Users/tfrescino/Documents/Fishlake/rawdata"
#AOInm <- "Fishlake"
#title.ref <- NULL

rawfolder <- params$rawfolder
AOInm <- params$AOInm
title.ref <- params$title.ref
outfolder <- params$outfolder


if (is.null(rawfolder)) stop()
if (is.null(AOInm)) stop()

if (is.null(title.ref)) title.ref <- AOInm
if (is.null(outfolder)) outfolder <- rawfolder


## Define function to create prettier tables
kable.table <- function(est, title.row, title.rowvar) {
    knitr::kable(est,
    #format = "pandoc",   # default
    format = "simple",   # default
    caption = wraptitle(title.row, 80),
    col.names = names(est),
    row.names = FALSE,
    align = c("r"),       # align = c("c", "c", "c", "r")
    digits = 2,
    format.args=list(decimal.mark = ",", big.mark=",")
    # padding = 2         # inner spacing
  ) 
}


```



```{r echo=FALSE, warning=FALSE, message=FALSE}


filelst <- list.files(rawfolder, pattern=c("area_COND_STATUS_NM", "csv"))
fn <- filelst[grep("unit.rowest", filelst)][1]


unit.est <- fread(file.path(rawfolder, fn))

title.rowvar <- names(unit.est)[2]
totarea <- unique(unit.est$ACRES_GIS)
area.for <- unit.est[unit.est[[title.rowvar]] == "Forest land", "est"]
area.nf <- unit.est[unit.est[[title.rowvar]] == "Nonforest land", "est"]
area.water <- sum(unit.est[unit.est[[title.rowvar]] %in% c("Noncensus water", "Nonforest land"), "est"])
est <- unit.est[, c(title.rowvar, "est", "pse"), with=FALSE]

title1 <- paste0("Area by land class, ", title.ref)


```


&nbsp;
&nbsp;
&nbsp;


The area of `r params$AOInm` is `r format(round(totarea), big.mark=",")` acres with `r round(area.for/totarea * 100)` percent of the area classified as forest land, `r round(area.nf/totarea * 100)` percent classified as nonforest land, and `r round(area.water/totarea * 100)` percent as water (Fig. 1).


&nbsp;
&nbsp;
&nbsp;
&nbsp;


```{r echo=FALSE, warning=FALSE, message=FALSE}

## Create prettier table
kable.table(est, paste("Table 1.", title1), title.rowvar)



```


&nbsp;
&nbsp;



```{r echo=FALSE, warning=FALSE, message=FALSE, fig.cap=paste("Fig. 1.", title1)}

datBarplot(x=unit.est, xvar=names(unit.est)[2], yvar="est", errbars=TRUE, 
           sevar="est.se", x.order=NULL, las.xnames=2, ylabel="Area - Acres", 
           col=hcl.colors(nrow(unit.est)), ylim=NULL, toplabelvar="NBRPLT.gt0")


```


&nbsp;
&nbsp;

