---
title: "FIESTA - Small Area Estimators"
#output: rmarkdown::html_vignette

output:
  rmarkdown::html_vignette:
    smart: FALSE
    toc: TRUE
 #   toc_float: TRUE
vignette: >
  %\VignetteIndexEntry{FIESTA - Small Area Estimators}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---


## FIESTA Overview
The R package, FIESTA (Forest Inventory ESTimation and Analysis) is a research estimation tool for analysts that work with sample-based inventory data from the U.S. Department of Agriculture, Forest Service, Forest Inventory and Analysis (FIA) Program to accommodate: unique population boundaries, different evaluation time periods, customized stratification schemes, non-standard variance equations, integration of multi-scale remotely-sensed data and other ancillary information, and interaction with other modeling and estimation tools from CRAN R's library of packages. FIESTA contains a collection of functions that can access FIA databases, summarize and compile plot and spatial data, and generate estimates with associated sampling errors. 


Functions are organized by type or objective and are named with a corresponding prefix: 

**Core Functions**

* Database tools (DB) - functions for querying and extracting data from FIA's national database.
* Data tools (dat) - functions for summarizing and exploring FIA data.
* Spatial tools (sp) - functions for manipulating and summarizing spatial data.

**Estimation Modules**

* Green-Book (GB) - functions for FIA's standard Green-Book estimators.
* Photo-Based (PB) - functions for supplementary photo-based estimators.
* Small Area (SA) - functions for integration with available small area estimators (SAE).
* Model-Assisted (MA) - functions for integration with available Model-Assisted estimators.

**Analysis Tools**

* Analysis tools (an) - wrapper functions for steam-lining estimation processes.



### Small Area (SA) module overview
FIESTA's Small Area (SA) module was set up as a platform to integrate with current Small Area Estimators available on CRAN including the JoSAE (Breidenbach 2015) and sae (Molina and Marhuenda 2015) packages that use unit-level and area-level Empirical Best Linear Unbiased Prediction (EBLUP) estimation strategy for balancing potential bias of synthetic estimators against the instability of a direct estimator (Rao 2003). The module includes functional steps for checking, compiling, and formatting FIA plot data and ancillary spatial information for input to R packages, such as JoSAE (Breidenbach 2015) or sae (Molina and Marhuenda 2015) and translates integrated package output to FIESTA output format. 

### Objective of tutorial
The main objective of this tutorial is to demonstrate how to use FIESTA for generating estimates using estimators from JoSAE and sae. The following examples are for generating estimates and estimated variances using standard FIA Evaluation data from FIA's National database, with custom Estimation unit and Stratification information. The examples use data from three inventory years of field measurements in the state of Wyoming, from FIADB_1.7.2.00, last updated June 20, 2018, downloaded on June 25, 2018 and stored as internal data objects in FIESTA.


## Example data - Wyoming (WY), Inventory Years 2011-2012

Data Frame | Description
-----------| --------------------------------------------------------------------------------
WYplt      | WY plot-level data
WYcond     | WY condition-level data
WYtree     | WY tree-level data

External data            | Description
-------------------------| ------------------------------------------------------------------
WYbighorn_adminbnd.shp   | Polygon shapefile of WY Bighorn National Forest Administrative boundary*
WYbighorn_districtbnd.shp| Polygon shapefile of WY Bighorn National Forest District boundaries**
WYbighorn_forest_nonforest_250m.tif| GeoTIFF raster of predicted forest/nonforest (1/0) for stratification*** 
WYbighorn_dem_250m.img   | Erdas Imagine raster of elevation change, in meters****

*USDA Forest Service, Automated Lands Program (ALP). 2018. S_USA.AdministrativeForest (\url{http://data.fs.usda.gov/geodata/edw}). Description: An area encompassing all the National Forest System lands administered by an administrative unit. The area encompasses private lands, other governmental agency lands, and may contain National Forest System lands within the proclaimed boundaries of another administrative unit. All National Forest System lands fall within one and only one Administrative Forest Area.

**USDA Forest Service, Automated Lands Program (ALP). 2018. S_USA.RangerDistrict (http://data.fs.usda.gov/geodata/edw). Description: A depiction of the boundary that encompasses a Ranger District.

***Based on MODIS-based classified map resampled from 250m to 500m resolution and reclassified from 3 to 2 classes: 1:forest; 2:nonforest. Projected in Albers Conical Equal Area, Datum NAD27 (Ruefenacht et al. 2008). Clipped to extent of WYbighorn_adminbnd.shp.

****USGS National Elevation Dataset (NED), resampled from 30m resolution to 250m. Projected in Albers Conical Equal Area, Datum NAD27 (U.S. Geological Survey 2017). Clipped to boundary of WYbighorn_adminbnd.shp.



FUNCTION  | DESCRIPTION
-------------- | ---------------------------------------------------------------
[spGetSAdoms()](#spGetSAdoms) | Gets small area domains for estimation.
[spGetDBbnd()](#spGetDBbnd)| Gets data from FIA database for plots within a given boundary.
[spGetModeldat()](#spGetModeldat)| Gets plot and spatial data for small area models.
[modSAtree()](#modSAtree)| Generate tree estimates using Small Area Estimation (SAE) methods.


### EXAMPLES

Set up for examples
```
# Load library
library(FIESTA)
library(sae)
library(JoSAE)
library(nlme)


# Set workspace to FIESTA folder (create if doesn't exist)
if (!file.exists("C:/FIESTA"))  dir.create("C:/FIESTA")
setwd("C:/FIESTA")

# Create 2 subfolders under the FIESTA folder, 'data' and 'outfolder' and set path to objects 
if (!file.exists("data"))  dir.create("data")
datfolder <- "data" 

if (!file.exists("outfolder")) dir.create("outfolder")
outfolder <- "outfolder"

# File names for external spatial data
WYbhfn <- system.file("extdata", "sp_data/WYbighorn_adminbnd.shp", package="FIESTA")
WYbhdistfn <- system.file("extdata", "sp_data/WYbighorn_districtbnd.shp", package="FIESTA")
WYbhdist.att <- "DISTRICTNA"

fornffn <- system.file("extdata", "sp_data/WYbighorn_forest_nonforest_250m.tif", package="FIESTA")
demfn <- system.file("extdata", "sp_data/WYbighorn_dem_250m.img", package="FIESTA")

# Derive new layers from dem
library(raster)
dem <- raster(demfn)
slp <- terrain(dem, opt="slope", unit="degrees", filename=paste0(outfolder, "/WYbh_slp.img"), overwrite=TRUE)
asp <- terrain(dem, opt="aspect", unit="degrees", filename=paste0(outfolder, "/WYbh_asp.img"), overwrite=TRUE)


```


<a name="ref"></a>

## Reference Tables in FIESTA

There are several reference tables stored in FIESTA, including table variable descriptions, code definitions, and estimation categories. 

* Table variable descriptions - ref_plt, ref_cond, ref_tree
* Code definitions - ref_codes


<a name="auxiliary"></a>


#### <a name="spGetSAdoms"/>spGetSAdoms()
```
######################################################################################
# Usage:
# spGetSAdoms(smallbnd_layer, smallbnd_dsn = NULL, smallbnd.att, 
#	  smallbnd.name = NULL, smallbnd.filter = NULL, helperbnd_layer = NULL, 
#	  helperbnd_dsn = NULL, helperbnd.att = NULL, helperbnd.name = NULL, 
#	  helperbnd.filter = NULL, largebnd_layer = NULL, largebnd_dsn = NULL, 
#	  largebnd.att = NULL, largebnd.name = NULL, largebnd.filter = NULL, 
#	  exportshp = FALSE, outfolder = NULL, outfn = NULL, outfn.date = TRUE, 
#	  overwrite = FALSE)
# 
# Description:
# Get spatial domains for small area estimation.
######################################################################################
help(spGetSAdoms)

WYbhdist <- spImportSpatial(WYbhdistfn)
head(WYbhdist@data)

## Get spatial domains for small area estimation
SAdoms <- spGetSAdoms(smallbnd_layer=WYbhdistfn, smallbnd.att="DISTRICTNA")
SAdoms@data
sp::plot(SAdoms)


```

#### <a name="spGetDBbnd"/>spGetDBbnd()
```
######################################################################################
# Usage:
# spGetDBbnd(bnd_layer, bnd_dsn = NULL, stbnd = NULL, states = NULL,  
#	    RMRSonly = TRUE, datsource = "ORACLE", FS_FIADB = FALSE, SQLitefn = NULL,  
#	    evalCur = TRUE, evalEndyr = NULL, evalType = "all", actual = FALSE,  
#	    coordsfn = NULL, coordsfn.uniqueid = NULL, savedata = FALSE,  
#	    exportshp = FALSE, outfolder = NULL, overwrite = FALSE, outfn = NULL,  
#	    outfn.pre = NULL, datPlots = NULL, CTcoverfn = NULL, ...) 
# 
# Description:
# Extract data from FIA database for plots within a given boundary.
######################################################################################
bnd_layer=SAdoms
FS_FIADB=TRUE
states="Wyoming"
datsource="CSV"

SAdata <- spGetDBbnd(bnd_layer=SAdoms, FS_FIADB=TRUE, states="Wyoming", datsource="CSV",
      invyrs=2011:2013)
names(SAdata)
SAbnd <- SAdata$clip_poly
SAspplt <- SAdata$clip_spplt
SAdata$coordtype

SAtabs <- SAdata$clip_tabs
names(SAtabs)
SAplt <- SAtabs$clip_plt
SAcond <- SAtabs$clip_cond
SAtree <- SAtabs$clip_tree
SAshp_PUBLIC <- SAtabs$clip_shp_PUBLIC

sp::plot(SAspplt)
sp::plot(SAbnd, add=TRUE)

table(SAplt$INVYR)

```


#### <a name="spGetModeldat"/>spGetModeldat()
```
######################################################################################
# Usage:
# spGetModeldat(spplt = NULL, spplt_dsn = NULL, xyplt = NULL, uniqueid = "PLT_CN",  
#   	domtype = "POLY", dom_dsn, dom_layer = NULL, unitvar = NULL, rastlst.cont = NULL,  
# 	  rastlst.cont.name = NULL, rastlst.cont.stat = "MEAN", rastlst.cat = NULL, 
#	    rastlst.cat.name = NULL, rastfolder = NULL, rast.NODATA = NULL,  
#     asptransform = FALSE, asprast = NULL, keepnull = FALSE, showext = TRUE,   
#   	savedata = FALSE, exportshp = FALSE, outfolder = NULL, outfn = NULL, 
#     overwrite = FALSE, ...) 
# 
# Description:
# Get data extraction and zonal statistics for Model-assisted or
#		Model-based (Small Area) Estimation. The major steps are as follows:
#   1) Check parameters 
#   2) Extract point values from domlayer
#   3) Set up output data structures
#   4) Extract point values and get zonal statistics from continuous raster layers
#   5) Extract point values and get zonal statistics from categorical raster layers
#   6) Get total acres from domlayer (if areacalc=TRUE)
######################################################################################

## Extract from raster predictor layers
#######################################################
rastlst.cont <- c(demfn, slp, asp)
rastlst.cont.name <- c("dem", "slp", "asp")
rastlst.cat <- fornffn
rastlst.cat.name="fornf"

modeldat <- spGetModeldat(spplt=SAspplt, uniqueid="PLT_CN", dom_layer=SAbnd,
  domvar="DOMAIN", rastlst.cont=rastlst.cont, rastlst.cont.name=rastlst.cont.name,
  rastlst.cat=rastlst.cat, rastlst.cat.name=rastlst.cat.name, rastlst.cont.stat="mean",
  rast.NODATA=0, asptransform=TRUE, rast.asp=asp, keepnull=FALSE, showext=FALSE,
  savedata=FALSE, vars2keep="AOI")
names(modeldat)

sppltmodel <- modeldat$sppltmodel
pltmodel <- modeldat$pltmodel
dunitlut <- modeldat$domzonal
dunitarea <- modeldat$domarea
dunitvar <- modeldat$domvar
areavar <- modeldat$areavar
inputdf <- modeldat$inputdf
prednames <- modeldat$prednames
dunitnames <- modeldat$zonalnames
predfac <- modeldat$predfac

dunitlut
dunitvar
areavar
head(pltmodel)
prednames
dunitnames
dunitarea


```

#### <a name="modSAtree"/>modSAtree()
```
######################################################################################
# Usage:
# modSAtree(tree, cond=NULL, pltmodel=NULL, tuniqueid="PLT_CN", 
#	  cuniqueid="PLT_CN", puniqueid="PLT_CN", sumunits=FALSE, adjplot=TRUE, 
#	  SApackage="JoSAE", SAmethod="unit", landarea="ALL", ACI=FALSE, 
#	  nonsamp.filter=NULL, plt.filter=NULL, cond.filter=NULL, domarea=NULL, 
#	  domvar="DOMAIN", areavar=NULL, domzonal=NULL, npixelvar="npixels",  
#	  prednames=NULL, predfac=NULL, estvar=NULL, estvar.filter=NULL, 
#   allin1=FALSE, estround=0, pseround=3, divideby=NULL, savedata=FALSE, 
#   rawdata=FALSE, outfolder=NULL, outfn=NULL, outfn.pre=NULL, 
#   outfn.date=TRUE, overwrite=FALSE, addtitle=TRUE, returntitle=FALSE, 
#   title.main=NULL, title.ref=NULL, title.unitvar=NULL, title.estvar=NULL,
#   title.filter=NULL, gui=FALSE) 
# 
# Description:
# Generate estimates for area of interest, or small boundary.
######################################################################################


## Estimates of live basal area (sq cuft) by Bighorn National Forest district
estvar <- "BA"
#prednames <- prednames[1:3]   ## Note: not yet working with factor variables
estvar.filter <- "STATUSCD == 1"
tree=SAtree
cond=SAcond
pltmodel=sppltmodel
adjplot=TRUE
SAmethod="area"
SApackage="JoSAE"

SAdat <- modSAtree(tree=SAtree, cond=SAcond, pltmodel=sppltmodel,
  dunitarea=dunitarea, areavar=areavar, dunitlut=dunitlut, 
  prednames=prednames, predfac=predfac,
  estvar=estvar, estvar.filter=estvar.filter, rawdata=TRUE)

names(SAdat)
SAdat$est
SAdat.raw <- SAdat$raw
names(SAdat.raw)


SAdat.raw$plotsampcnt
SAdat.raw$condsampcnt

SAdat.raw$domzonal
SAdat.raw$domarea
head(SAdat.raw$tdomdat)
SAdat.raw$estvar

SAdat.raw$JoSAE.unit
SAdat.raw$JoSAE.unit.lme


```



## References

Breidenbach J. 2018. JoSAE: Unit-Level and Area-Level Small Area Estimation.

Molina I, Marhuenda Y. 2015. sae: An R Package for Small Area Estimation. The R Journal, 7(1), 81–98. https://journal.r-project.org/archive/2015/RJ-2015-007/RJ-2015-007.pdf.

Rao, J.N.K. 2003. Small Area Estimation. Wiley, Hoboken, New Jersey.

