# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RasterizePolygon <- function(nRasterXSize, nRasterYSize, ivPartSizes, dvX, dvY, fnRasterIO, dBurnValue, sAttrValue = NA_character_) {
    .Call('_FIESTA_RasterizePolygon', PACKAGE = 'FIESTA', nRasterXSize, nRasterYSize, ivPartSizes, dvX, dvY, fnRasterIO, dBurnValue, sAttrValue)
}

